/*
 * Dikembangkan untuk keperluan proyek Magang D3 TI UNS tahun 2014.
 * bustomiraharjo@gmail.com
 * Bustomi Raharjo | M3112150 | D3 TI-C FMIPA UNS 2012 \^_^v
 */

package com.bustomi.bookstorepos.view.panel;

import com.bustomi.bookstorepos.entity.laporan.Keuntungan;
import com.bustomi.bookstorepos.entity.transaksi.Pembelian;
import com.bustomi.bookstorepos.entity.transaksi.Penjualan;
import com.bustomi.bookstorepos.manager.SpringManager;
import com.bustomi.bookstorepos.service.PembelianService;
import com.bustomi.bookstorepos.service.PenjualanService;
import com.bustomi.bookstorepos.view.dialog.DialogLaporan;
import com.bustomi.bookstorepos.view.tablemodel.HurufRender;
import com.bustomi.bookstorepos.view.tablemodel.TabelModelKeuntungan;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.io.InputStream;
import java.math.BigDecimal;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;

/**
 *
 * @author PacuL
 */
public class PanelKeuntungan extends javax.swing.JPanel {

    private final TabelModelKeuntungan modelKeuntungan;
    private Date mulai;
    private Date sampai;
    private boolean filter=false;
    private List<Keuntungan> list;
    
    public PanelKeuntungan()  {
        
        modelKeuntungan=new TabelModelKeuntungan();
        initComponents();
        
        TabelKeuntungan.setModel(modelKeuntungan);
        
        TabelKeuntungan.getColumnModel().getColumn(0).setMaxWidth(50);
        TabelKeuntungan.getColumnModel().getColumn(0).setCellRenderer(new HurufRender());
        TabelKeuntungan.getColumnModel().getColumn(1).setCellRenderer(new HurufRender());
        TabelKeuntungan.getColumnModel().getColumn(2).setCellRenderer(new HurufRender());
        TabelKeuntungan.getColumnModel().getColumn(3).setCellRenderer(new HurufRender());  
        TabelKeuntungan.getColumnModel().getColumn(4).setCellRenderer(new HurufRender());         
        TabelKeuntungan.getColumnModel().getColumn(5).setCellRenderer(new HurufRender()); 
        TabelKeuntungan.getColumnModel().getColumn(6).setCellRenderer(new HurufRender());           
        TabelKeuntungan.getColumnModel().getColumn(7).setCellRenderer(new HurufRender()); 
        TabelKeuntungan.getColumnModel().getColumn(8).setCellRenderer(new HurufRender()); 
        TabelKeuntungan.getTableHeader().setAlignmentY(CENTER_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPortX1 = new com.bustomi.bookstorepos.component.ViewPortX();
        TabelKeuntungan = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        panelX2 = new com.bustomi.bookstorepos.component.PanelX();
        jLabel2 = new javax.swing.JLabel();
        buttonMin2 = new com.bustomi.bookstorepos.component.ButtonMin();
        jDateChooserMulai = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserSampai = new com.toedter.calendar.JDateChooser();
        buttonRed1 = new com.bustomi.bookstorepos.component.ButtonRed();

        TabelKeuntungan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelKeuntungan.setOpaque(false);
        viewPortX1.add(TabelKeuntungan);

        setOpaque(false);

        jScrollPane1.setOpaque(false);
        jScrollPane1.setViewport(viewPortX1);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DAFTAR KEUNTUNGAN");

        panelX2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mulai :");

        buttonMin2.setText("Filter");
        buttonMin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMin2ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sampai :");

        javax.swing.GroupLayout panelX2Layout = new javax.swing.GroupLayout(panelX2);
        panelX2.setLayout(panelX2Layout);
        panelX2Layout.setHorizontalGroup(
            panelX2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelX2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooserMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooserSampai, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelX2Layout.setVerticalGroup(
            panelX2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelX2Layout.createSequentialGroup()
                .addGroup(panelX2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelX2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(buttonMin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelX2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelX2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jDateChooserSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(6, 6, 6))
        );

        buttonRed1.setText("CETAK LAPORAN");
        buttonRed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRed1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(buttonRed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 421, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRed1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMin2ActionPerformed
        mulai=jDateChooserMulai.getDate();
        sampai=jDateChooserSampai.getDate();
        
        if (mulai == null) {
            JOptionPane.showMessageDialog(this, "Tanggal 'mulai' belum dipilih!");
        } else if (sampai == null){
            JOptionPane.showMessageDialog(this, "Tanggal 'sampai' belum dipilih");            
        } else {
             filter = true;
            PenjualanService service=SpringManager.getInstance().getBean(PenjualanService.class);
            PembelianService pembelianService=SpringManager.getInstance().getBean(PembelianService.class);
            List<Pembelian> pembelians=pembelianService.findAll(mulai, sampai);
            List<Penjualan> penjualans=service.findAll(mulai,sampai);
            list = new ArrayList<>(pembelians.size() + penjualans.size());
            
            for (Penjualan penjualan : penjualans) {
                Keuntungan keuntungan=new Keuntungan(penjualan);
                list.add(keuntungan);
            }
            
            for (Pembelian pembelian : pembelians) {
                Keuntungan keuntungan = new Keuntungan(pembelian);
                list.add(keuntungan);
            }
            
            Collections.sort(list, new Comparator<Keuntungan>() {

                @Override
                public int compare(Keuntungan o1, Keuntungan o2){
                    return o1.getTanggal().compareTo(o2.getTanggal());
                }
            });
            
//            for (int i = 0; i < list.size(); i++) {
//                Keuntungan keuntungan=list.get(i);
//                if (i != 0) {
//                    Keuntungan sebelum=list.get(i-1);
//                    if (keuntungan.getJenis().equals("Penjualan")) {
//                        keuntungan.setKeuntungan(sebelum.getKeuntungan().add(keuntungan.getTotal()));
//                    }else {
//                        keuntungan.setKeuntungan(sebelum.getKeuntungan().subtract(keuntungan.getTotal()));
//                    }
//                }else{
//                    if (keuntungan.getJenis().equals("Penjualan")) {
//                        keuntungan.setKeuntungan(BigDecimal.ZERO.add(keuntungan.getTotal()));
//                    }else {
//                        keuntungan.setKeuntungan(BigDecimal.ZERO.subtract(keuntungan.getTotal()));
//                    }
//                }
//            }
            
            modelKeuntungan.load(list);
        }
    }//GEN-LAST:event_buttonMin2ActionPerformed

    private void buttonRed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRed1ActionPerformed
        if (!filter) {
            JOptionPane.showMessageDialog(this, "Silahkan filter data keuntungan");
        }else if (modelKeuntungan.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Daftar keuntungan kosong");
        } else {
            int pilih=JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin mencetak dari tanggal "+mulai+
                    " sampai tanggal "+sampai+" ?", "Pertanyaan?", JOptionPane.YES_NO_OPTION);
            if (pilih == JOptionPane.YES_OPTION) {
                
                try {
                    InputStream inputStream=PanelKeuntungan.class.getResourceAsStream("/com/bustomi/d3ti/uns/report/keuntungan.jasper");

                    JRDataSource dataSource=new JRBeanCollectionDataSource(modelKeuntungan.getList(), false);
                    Map<String, Object> map=new HashMap<>();
                    map.put("FROM", mulai);
                    map.put("TO", sampai);
                    map.put(JRParameter.REPORT_LOCALE, new Locale("in", "ID"));

                    JasperPrint jasperPrint=JasperFillManager.fillReport(inputStream, map,dataSource);
                    DialogLaporan dialogLaporan=new DialogLaporan(jasperPrint);
                    dialogLaporan.setLocationRelativeTo(null);
                    dialogLaporan.setVisible(true);
                } catch (JRException ex) {
                    Logger.getLogger(PanelKeuntungan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
              
            
        }
    }//GEN-LAST:event_buttonRed1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelKeuntungan;
    private com.bustomi.bookstorepos.component.ButtonMin buttonMin2;
    private com.bustomi.bookstorepos.component.ButtonRed buttonRed1;
    private com.toedter.calendar.JDateChooser jDateChooserMulai;
    private com.toedter.calendar.JDateChooser jDateChooserSampai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.bustomi.bookstorepos.component.PanelX panelX2;
    private com.bustomi.bookstorepos.component.ViewPortX viewPortX1;
    // End of variables declaration//GEN-END:variables
    
}
