/*
 * Dikembangkan untuk keperluan proyek Magang D3 TI UNS tahun 2014.
 * bustomiraharjo@gmail.com
 * Bustomi Raharjo | M3112150 | D3 TI-C FMIPA UNS 2012 \^_^v
 */

package com.bustomi.bookstorepos.view.panel;

import com.bustomi.bookstorepos.entity.master.Item;
import com.bustomi.bookstorepos.entity.master.Pelanggan;
import com.bustomi.bookstorepos.entity.transaksi.DetailPenjualan;
import com.bustomi.bookstorepos.entity.transaksi.Penjualan;
import com.bustomi.bookstorepos.manager.LoginManager;
import com.bustomi.bookstorepos.manager.SpringManager;
import com.bustomi.bookstorepos.service.ItemService;
import com.bustomi.bookstorepos.service.PelangganService;
import com.bustomi.bookstorepos.service.PenjualanService;
import com.bustomi.bookstorepos.view.dialog.DialogCariDataPembelian;
import com.bustomi.bookstorepos.view.dialog.DialogCariDataPenjualan;
import com.bustomi.bookstorepos.view.dialog.DialogCariPelanggan;
import com.bustomi.bookstorepos.view.dialog.DialogLaporan;
import com.bustomi.bookstorepos.view.tablemodel.HurufRender;
import com.bustomi.bookstorepos.view.tablemodel.TabelModelDetailPenjualan;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.io.InputStream;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.jdbc.Work;

/**
 *
 * @author PacuL
 */
public class PanelTransPenjualan extends javax.swing.JPanel {

    private final TabelModelDetailPenjualan modelPenjualan;
    private Pelanggan pelanggan;
    private BigDecimal total;
    private boolean simpan;
    
    public PanelTransPenjualan()  {
        
        modelPenjualan=new TabelModelDetailPenjualan();
        
        initComponents();
        
        PelangganService pelangganService=SpringManager.getInstance().getBean(PelangganService.class);
        pelanggan = new Pelanggan();
        pelanggan=pelangganService.find("umum");
        textFieldXNamaPel.setText(pelanggan.getNama());
        
        TabelPenjualan.setModel(modelPenjualan);
        TabelPenjualan.getColumnModel().getColumn(0).setMaxWidth(50);         
        TabelPenjualan.getColumnModel().getColumn(0).setCellRenderer(new HurufRender());
        TabelPenjualan.getColumnModel().getColumn(1).setCellRenderer(new HurufRender());
        TabelPenjualan.getColumnModel().getColumn(2).setCellRenderer(new HurufRender());
        TabelPenjualan.getColumnModel().getColumn(3).setCellRenderer(new HurufRender());  
        TabelPenjualan.getColumnModel().getColumn(4).setCellRenderer(new HurufRender());         
        TabelPenjualan.getColumnModel().getColumn(5).setCellRenderer(new HurufRender());  
        TabelPenjualan.getTableHeader().setAlignmentY(CENTER_ALIGNMENT);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPortX1 = new com.bustomi.bookstorepos.component.ViewPortX();
        TabelPenjualan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        panelX3 = new com.bustomi.bookstorepos.component.PanelX();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        buttonRed1 = new com.bustomi.bookstorepos.component.ButtonRed();
        panelX4 = new com.bustomi.bookstorepos.component.PanelX();
        jLabel4 = new javax.swing.JLabel();
        textFieldXNamaPel = new com.bustomi.bookstorepos.component.TextFieldX();
        buttonGreen2 = new com.bustomi.bookstorepos.component.ButtonGreen();
        jLabel5 = new javax.swing.JLabel();
        textFieldXKodeItem = new com.bustomi.bookstorepos.component.TextFieldX();
        buttonGreen4 = new com.bustomi.bookstorepos.component.ButtonGreen();
        jLabel6 = new javax.swing.JLabel();
        textFormatXJmlhBeli = new com.bustomi.bookstorepos.component.TextFormatX();
        buttonYellow1 = new com.bustomi.bookstorepos.component.ButtonYellow();
        panelX5 = new com.bustomi.bookstorepos.component.PanelX();
        textFormatXKembali = new com.bustomi.bookstorepos.component.TextFormatX();
        panelX1 = new com.bustomi.bookstorepos.component.PanelX();
        textFormatXBayar = new com.bustomi.bookstorepos.component.TextFormatX();
        jLabel2 = new javax.swing.JLabel();
        panelX6 = new com.bustomi.bookstorepos.component.PanelX();
        textFormatXTotal = new com.bustomi.bookstorepos.component.TextFormatX();
        buttonBlue1 = new com.bustomi.bookstorepos.component.ButtonBlue();
        buttonRed2 = new com.bustomi.bookstorepos.component.ButtonRed();
        buttonGreen1 = new com.bustomi.bookstorepos.component.ButtonGreen();

        TabelPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelPenjualan.setOpaque(false);
        viewPortX1.add(TabelPenjualan);

        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSAKSI PENJUALAN");

        panelX3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daftar Pembelian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelX3.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setOpaque(false);
        jScrollPane1.setViewport(viewPortX1);

        jPanel1.setOpaque(false);

        buttonRed1.setText("Hapus Pembelian");
        buttonRed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRed1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRed1);

        javax.swing.GroupLayout panelX3Layout = new javax.swing.GroupLayout(panelX3);
        panelX3.setLayout(panelX3Layout);
        panelX3Layout.setHorizontalGroup(
            panelX3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelX3Layout.setVerticalGroup(
            panelX3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelX3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        panelX4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Penjualan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelX4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Pelanggan :");

        textFieldXNamaPel.setEnabled(false);

        buttonGreen2.setText("Cari");
        buttonGreen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGreen2ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Kode Item :");

        buttonGreen4.setText("Cari");
        buttonGreen4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGreen4ActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Jumlah Beli :");

        textFormatXJmlhBeli.setValue(new Integer(1));

        buttonYellow1.setText("Masukan ke Daftar Pembelian");
        buttonYellow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonYellow1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelX4Layout = new javax.swing.GroupLayout(panelX4);
        panelX4.setLayout(panelX4Layout);
        panelX4Layout.setHorizontalGroup(
            panelX4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelX4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelX4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelX4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelX4Layout.createSequentialGroup()
                        .addGroup(panelX4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldXNamaPel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldXKodeItem, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelX4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonGreen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonGreen4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelX4Layout.createSequentialGroup()
                        .addComponent(textFormatXJmlhBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonYellow1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
        );
        panelX4Layout.setVerticalGroup(
            panelX4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelX4Layout.createSequentialGroup()
                .addGroup(panelX4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldXNamaPel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(buttonGreen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelX4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldXKodeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGreen4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelX4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFormatXJmlhBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonYellow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        panelX5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Uang Kembalian (IDR)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelX5.setForeground(new java.awt.Color(255, 255, 255));

        textFormatXKembali.setForeground(new java.awt.Color(204, 0, 51));
        textFormatXKembali.setEnabled(false);
        textFormatXKembali.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textFormatXKembali.setValue(new BigDecimal(0.00)
        );
        textFormatXKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFormatXKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelX5Layout = new javax.swing.GroupLayout(panelX5);
        panelX5.setLayout(panelX5Layout);
        panelX5Layout.setHorizontalGroup(
            panelX5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textFormatXKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        );
        panelX5Layout.setVerticalGroup(
            panelX5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textFormatXKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE)
        );

        panelX1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Uang Pembayaran", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelX1.setForeground(new java.awt.Color(255, 255, 255));

        textFormatXBayar.setForeground(new java.awt.Color(51, 255, 51));
        textFormatXBayar.setValue(new BigDecimal(0.00));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Jumlah Bayar :");

        javax.swing.GroupLayout panelX1Layout = new javax.swing.GroupLayout(panelX1);
        panelX1.setLayout(panelX1Layout);
        panelX1Layout.setHorizontalGroup(
            panelX1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelX1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFormatXBayar, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelX1Layout.setVerticalGroup(
            panelX1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelX1Layout.createSequentialGroup()
                .addGroup(panelX1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFormatXBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        panelX6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Harga (IDR)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        panelX6.setForeground(new java.awt.Color(255, 255, 255));

        textFormatXTotal.setForeground(new java.awt.Color(204, 0, 51));
        textFormatXTotal.setEnabled(false);
        textFormatXTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textFormatXTotal.setValue(new BigDecimal(1.00));

        javax.swing.GroupLayout panelX6Layout = new javax.swing.GroupLayout(panelX6);
        panelX6.setLayout(panelX6Layout);
        panelX6Layout.setHorizontalGroup(
            panelX6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textFormatXTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        );
        panelX6Layout.setVerticalGroup(
            panelX6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textFormatXTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
        );

        buttonBlue1.setText("BAYAR");
        buttonBlue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBlue1ActionPerformed(evt);
            }
        });

        buttonRed2.setText("RESET");
        buttonRed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRed2ActionPerformed(evt);
            }
        });

        buttonGreen1.setText("BARU");
        buttonGreen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGreen1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelX3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelX5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelX6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonGreen1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonBlue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonRed2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 44, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(panelX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelX6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(panelX5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonGreen1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelX3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelX1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonBlue1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRed2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBlue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBlue1ActionPerformed
        final BigDecimal bayar=(BigDecimal) textFormatXBayar.getValue();
        BigDecimal kembali;
        
        if (pelanggan == null) {
            JOptionPane.showMessageDialog(this, "Pelanggan belum di pilih");
        }else if (modelPenjualan.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Belum ada item yang dibeli");
        } else if(bayar.compareTo(total) == -1){
            JOptionPane.showMessageDialog(this, "Jumlah bayar tidak cukup");
        }else {
            PenjualanService service=SpringManager.getInstance().getBean(PenjualanService.class);
            
            final Penjualan penjualan=new Penjualan();  
            penjualan.setPelanggan(pelanggan);
            penjualan.setUser(LoginManager.getInstance().getUser());
            penjualan.setWaktu_transaksi(new Date());
            penjualan.setTerakhir_diubah(new Date());
            penjualan.setUang(bayar);
             
            for (int i = 0; i < modelPenjualan.getRowCount(); i++) {
                DetailPenjualan detailPenjualan=modelPenjualan.ambilData(i);                
                penjualan.tambahDaftarPenjualan(detailPenjualan);
            }
            kembali=bayar.subtract(total);
            textFormatXKembali.setValue(kembali);
            service.save(penjualan);    
            modelPenjualan.hapusSemua();
            JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan"); 
            simpan=false;
            
            SessionFactory sessionFactory=SpringManager.getInstance().getBean(SessionFactory.class);
            Session session=sessionFactory.openSession();
            session.doWork(new Work() {

                @Override
                public void execute(Connection cnctn) throws SQLException {
                    try {
                        InputStream inputStream=getClass().getResourceAsStream
        ("/com/bustomi/d3ti/uns/report/StrukPenjualan.jasper");
                        
                        List<DetailPenjualan> list=penjualan.getDaftarPenjualan();
                        
                        JRDataSource dataSource=new JRBeanCollectionDataSource(list,false);
                        
                        Map<String, Object> map=new HashMap<>();
                        map.put("NO", penjualan.getId());
                        map.put("CASHIER", penjualan.getUser().getNama());
                        map.put("DATE", penjualan.getWaktu_transaksi());
                        map.put("TOTAL", penjualan.getTotal());
                        map.put("CASH", bayar);
                        map.put(JRParameter.REPORT_DATA_SOURCE, dataSource);
                        
                        JasperPrint jasperPrint=JasperFillManager.fillReport(inputStream, map);
                        DialogLaporan laporan=new DialogLaporan(jasperPrint);
                        laporan.setLocationRelativeTo(null);
                        laporan.setVisible(true);
                        
                    } catch (JRException ex) {
                        Logger.getLogger(PanelTransPenjualan.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            session.close();
        }
        
    }//GEN-LAST:event_buttonBlue1ActionPerformed

    private void buttonGreen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGreen2ActionPerformed
        DialogCariPelanggan dcp=new DialogCariPelanggan();
        dcp.setLocationRelativeTo(this);
        pelanggan=dcp.pilih();
        if (pelanggan != null) {
            textFieldXNamaPel.setText(pelanggan.getNama());
        }        
    }//GEN-LAST:event_buttonGreen2ActionPerformed

    private void buttonRed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRed1ActionPerformed
        if (TabelPenjualan.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data pembelian untuk dihapus");
        }else {
            int pilih=TabelPenjualan.convertRowIndexToModel(TabelPenjualan.getSelectedRow());
            modelPenjualan.hapus(pilih);
            modelPenjualan.fireTableDataChanged();
            total();
        }
    }//GEN-LAST:event_buttonRed1ActionPerformed

    private void buttonYellow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonYellow1ActionPerformed
        String kodeitem=textFieldXKodeItem.getText();
        Integer jmlhbeli=(Integer) textFormatXJmlhBeli.getValue();
        
        ItemService itemService=SpringManager.getInstance().getBean(ItemService.class);
        Item item=itemService.find(kodeitem);
        
        if (item == null) {
            JOptionPane.showMessageDialog(this, "Item yang dibeli tidak ditemukan");
        }else if(jmlhbeli < 1){
            JOptionPane.showMessageDialog(this, "Jumah beli minimal 1 (satu)");
        }else if(jmlhbeli > item.getStok()){
            JOptionPane.showMessageDialog(this, "Stok tidak mencukupi");
        }else {
            final DetailPenjualan detailPenjualan=new DetailPenjualan();
            detailPenjualan.setHarga(item.getHarga_jual());
            detailPenjualan.setItem(item);
            detailPenjualan.setJumlah(jmlhbeli);
            detailPenjualan.setNama(item.getNama());
            for (int i = 0; i < modelPenjualan.getRowCount(); i++) {
                DetailPenjualan dp=modelPenjualan.ambilData(i);
                if (Objects.equals(dp.getItem().getId(), detailPenjualan.getItem().getId())) {
                    detailPenjualan.setJumlah(dp.getJumlah() + detailPenjualan.getJumlah());
                    detailPenjualan.setNama(item.getNama());
                    modelPenjualan.hapus(i);
                    break;
                }
            }            
            modelPenjualan.tambah(detailPenjualan);
            simpan=true;
            total();
            textFieldXKodeItem.setText("");
            textFormatXJmlhBeli.setValue(1);
        }
    }//GEN-LAST:event_buttonYellow1ActionPerformed

    private void buttonGreen4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGreen4ActionPerformed
        DialogCariDataPenjualan dataBeli=new DialogCariDataPenjualan();
        dataBeli.setLocationRelativeTo(this);
        Item item=dataBeli.pilih();
        if (item != null) {
            textFieldXKodeItem.setText(item.getId());
        }
    }//GEN-LAST:event_buttonGreen4ActionPerformed

    private void textFormatXKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFormatXKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFormatXKembaliActionPerformed

    private void buttonRed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRed2ActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin reset?", "Konfirmasi reset",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            reset();
        }
        
    }//GEN-LAST:event_buttonRed2ActionPerformed

    private void buttonGreen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGreen1ActionPerformed
        if (simpan) {
            if (JOptionPane.showConfirmDialog(this, "Terdapat transaksi yang belum disimpan."
                    + "\nBuat transaksi baru?", "Konfirmasi transaksi baru",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                reset();
            }
        }else{
            reset();
        }
    }//GEN-LAST:event_buttonGreen1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPenjualan;
    private com.bustomi.bookstorepos.component.ButtonBlue buttonBlue1;
    private com.bustomi.bookstorepos.component.ButtonGreen buttonGreen1;
    private com.bustomi.bookstorepos.component.ButtonGreen buttonGreen2;
    private com.bustomi.bookstorepos.component.ButtonGreen buttonGreen4;
    private com.bustomi.bookstorepos.component.ButtonRed buttonRed1;
    private com.bustomi.bookstorepos.component.ButtonRed buttonRed2;
    private com.bustomi.bookstorepos.component.ButtonYellow buttonYellow1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.bustomi.bookstorepos.component.PanelX panelX1;
    private com.bustomi.bookstorepos.component.PanelX panelX3;
    private com.bustomi.bookstorepos.component.PanelX panelX4;
    private com.bustomi.bookstorepos.component.PanelX panelX5;
    private com.bustomi.bookstorepos.component.PanelX panelX6;
    private com.bustomi.bookstorepos.component.TextFieldX textFieldXKodeItem;
    private com.bustomi.bookstorepos.component.TextFieldX textFieldXNamaPel;
    private com.bustomi.bookstorepos.component.TextFormatX textFormatXBayar;
    private com.bustomi.bookstorepos.component.TextFormatX textFormatXJmlhBeli;
    private com.bustomi.bookstorepos.component.TextFormatX textFormatXKembali;
    private com.bustomi.bookstorepos.component.TextFormatX textFormatXTotal;
    private com.bustomi.bookstorepos.component.ViewPortX viewPortX1;
    // End of variables declaration//GEN-END:variables
 
    private BigDecimal total() {
        total = BigDecimal.ZERO;
        for (int i = 0; i < modelPenjualan.getRowCount(); i++) {
            DetailPenjualan detailPenjualan = modelPenjualan.ambilData(i);
            total = total.add(detailPenjualan.getSubTotal());
        }
        textFormatXTotal.setValue(total);
        return total;
    }   
    
    private void reset(){
        simpan=false;
        textFieldXKodeItem.setText("");
        textFormatXJmlhBeli.setValue(1);
        textFormatXBayar.setValue(BigDecimal.ZERO);
        textFormatXTotal.setValue(new BigDecimal(BigInteger.ZERO));
        textFormatXKembali.setValue(new BigDecimal(BigInteger.ZERO));
        modelPenjualan.hapusSemua();
    }
}
