/*
 * Dikembangkan untuk keperluan proyek Magang D3 TI UNS tahun 2014.
 * bustomiraharjo@gmail.com
 * Bustomi Raharjo | M3112150 | D3 TI-C FMIPA UNS 2012 \^_^v
 */

package com.bustomi.bookstorepos.view.dialog;

import com.bustomi.bookstorepos.entity.master.Barang;
import com.bustomi.bookstorepos.entity.master.Buku;
import com.bustomi.bookstorepos.entity.master.Item;
import com.bustomi.bookstorepos.entity.transaksi.DetailPembelian;
import com.bustomi.bookstorepos.manager.SpringManager;
import com.bustomi.bookstorepos.service.BarangService;
import com.bustomi.bookstorepos.service.BukuService;
import com.bustomi.bookstorepos.service.ItemService;
import com.bustomi.bookstorepos.view.tablemodel.HurufRender;
import com.bustomi.bookstorepos.view.tablemodel.TabelModelItem;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author PacuL
 */
public class DialogCariDataPembelian extends javax.swing.JDialog {

    private TabelModelItem modelItem;
    private Item item;
    private DetailPembelian detailPembelian;
    private boolean beli;
    
    public DialogCariDataPembelian() {
        setModal(true);
        initComponents();
        modelItem=new TabelModelItem();
        jTable1.setModel(modelItem);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(new HurufRender());
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new HurufRender());
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new HurufRender());
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new HurufRender());  
        jTable1.getColumnModel().getColumn(4).setCellRenderer(new HurufRender()); 
        
    }
    
    public Item pilih(){
        beli = true;
        setVisible(true);       
        
        return item;
    }
    
    public DetailPembelian pilihPembelian(){
        beli = false;
        setVisible(true);
        textFormatXJmlh.setEnabled(true);
        return detailPembelian;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPortX1 = new com.bustomi.bookstorepos.component.ViewPortX();
        jTable1 = new javax.swing.JTable();
        panelXBack1 = new com.bustomi.bookstorepos.component.PanelXBack();
        panelX1 = new com.bustomi.bookstorepos.component.PanelX();
        jLabel1 = new javax.swing.JLabel();
        textFieldXNama = new com.bustomi.bookstorepos.component.TextFieldX();
        buttonMin1 = new com.bustomi.bookstorepos.component.ButtonMin();
        jLabelInfo = new javax.swing.JLabel();
        panelX2 = new com.bustomi.bookstorepos.component.PanelX();
        buttonYellow1 = new com.bustomi.bookstorepos.component.ButtonYellow();
        buttonRed1 = new com.bustomi.bookstorepos.component.ButtonRed();
        jScrollPaneDaftar1 = new javax.swing.JScrollPane();
        panelX4 = new com.bustomi.bookstorepos.component.PanelX();
        textFormatXJmlh = new com.bustomi.bookstorepos.component.TextFormatX();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setOpaque(false);
        viewPortX1.add(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelX1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filter Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 255, 255)));
        panelX1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nama/Judul :");

        textFieldXNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldXNamaKeyPressed(evt);
            }
        });

        buttonMin1.setText("Filter");
        buttonMin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelX1Layout = new javax.swing.GroupLayout(panelX1);
        panelX1.setLayout(panelX1Layout);
        panelX1Layout.setHorizontalGroup(
            panelX1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelX1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldXNama, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonMin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelX1Layout.setVerticalGroup(
            panelX1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelX1Layout.createSequentialGroup()
                .addGroup(panelX1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldXNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buttonMin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jLabelInfo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelInfo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo.setText("Cari Item");
        jLabelInfo.setName(""); // NOI18N

        panelX2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        buttonYellow1.setText("Pilih");
        buttonYellow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonYellow1ActionPerformed(evt);
            }
        });
        panelX2.add(buttonYellow1);

        buttonRed1.setText("Batal");
        buttonRed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRed1ActionPerformed(evt);
            }
        });
        panelX2.add(buttonRed1);

        jScrollPaneDaftar1.setOpaque(false);
        jScrollPaneDaftar1.setViewport(viewPortX1);

        panelX4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        textFormatXJmlh.setValue(new Integer(1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jumlah Beli :");

        javax.swing.GroupLayout panelX4Layout = new javax.swing.GroupLayout(panelX4);
        panelX4.setLayout(panelX4Layout);
        panelX4Layout.setHorizontalGroup(
            panelX4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelX4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textFormatXJmlh, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelX4Layout.setVerticalGroup(
            panelX4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelX4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelX4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFormatXJmlh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)))
        );

        javax.swing.GroupLayout panelXBack1Layout = new javax.swing.GroupLayout(panelXBack1);
        panelXBack1.setLayout(panelXBack1Layout);
        panelXBack1Layout.setHorizontalGroup(
            panelXBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXBack1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelXBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDaftar1)
                    .addGroup(panelXBack1Layout.createSequentialGroup()
                        .addComponent(panelX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(panelXBack1Layout.createSequentialGroup()
                        .addComponent(panelX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelX2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelXBack1Layout.setVerticalGroup(
            panelXBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXBack1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelX1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDaftar1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelXBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelX4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelX2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(panelXBack1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        item=null;
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void buttonMin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMin1ActionPerformed
        cari();       
        
    }//GEN-LAST:event_buttonMin1ActionPerformed

    private void buttonYellow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonYellow1ActionPerformed
        Integer jmlh=(Integer) textFormatXJmlh.getValue();
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Barang pembelian belum dipilih");
        }else {
            int pilih=jTable1.convertRowIndexToModel(jTable1.getSelectedRow());            
            if (beli) {
                item=modelItem.ambilData(pilih);
                dispose();
            } else {
                if(jmlh < 1){
                    JOptionPane.showMessageDialog(this, "Jumlah pembelian minimal 1");
                } else{
                    detailPembelian = new DetailPembelian();                    
                    detailPembelian.setHarga(modelItem.ambilData(pilih).getHarga_beli());
                    detailPembelian.setJumlah(jmlh);
                    detailPembelian.setItem(modelItem.ambilData(pilih));
                    dispose();
                }
            }
            
        }
    }//GEN-LAST:event_buttonYellow1ActionPerformed

    private void buttonRed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRed1ActionPerformed
        item=null;
        detailPembelian=null;
        dispose();
    }//GEN-LAST:event_buttonRed1ActionPerformed

    private void textFieldXNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldXNamaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cari();
        }
    }//GEN-LAST:event_textFieldXNamaKeyPressed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bustomi.bookstorepos.component.ButtonMin buttonMin1;
    private com.bustomi.bookstorepos.component.ButtonRed buttonRed1;
    private com.bustomi.bookstorepos.component.ButtonYellow buttonYellow1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JScrollPane jScrollPaneDaftar1;
    private javax.swing.JTable jTable1;
    private com.bustomi.bookstorepos.component.PanelX panelX1;
    private com.bustomi.bookstorepos.component.PanelX panelX2;
    private com.bustomi.bookstorepos.component.PanelX panelX4;
    private com.bustomi.bookstorepos.component.PanelXBack panelXBack1;
    private com.bustomi.bookstorepos.component.TextFieldX textFieldXNama;
    private com.bustomi.bookstorepos.component.TextFormatX textFormatXJmlh;
    private com.bustomi.bookstorepos.component.ViewPortX viewPortX1;
    // End of variables declaration//GEN-END:variables
    
    private void load(){
        ItemService service=SpringManager.getInstance().getBean(ItemService.class);
        List<Item> list=service.findAll();
        modelItem.load(list);
    }
    
   private void cari(){
        final String nama=textFieldXNama.getText();
        
        if (nama.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Masukan nama pencarian");
        }else {                       
            buttonMin1.setEnabled(false);
            buttonYellow1.setEnabled(false);
                        
            new SwingWorker<List<Item>, Object>() {

                @Override
                protected List<Item> doInBackground() throws Exception {
                    ItemService itemService=SpringManager.getInstance().getBean(ItemService.class);
                    List<Item> items=itemService.findAll(nama); 
                    return items;
                }

                @Override
                protected void done() {
                    try {
                        if (get().size() < 1) {
                            JOptionPane.showMessageDialog(null, "Pencarian dengan kata kunci '"+nama+"' tidak ditemukan");
                        }else{
                            for (Item item : get()) {
                                modelItem.tambah(item);
                            }
                        }
                        buttonMin1.setEnabled(true);
                        buttonYellow1.setEnabled(true);
                    } catch (                InterruptedException | ExecutionException ex) {
                        Logger.getLogger(DialogCariDataPenjualan.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }       
            }.execute();            
        }
    }
}
