/*
 * Dikembangkan untuk keperluan proyek Magang D3 TI UNS tahun 2014.
 * bustomiraharjo@gmail.com
 * Bustomi Raharjo | M3112150 | D3 TI-C FMIPA UNS 2012 \^_^v
 */

package com.bustomi.bookstorepos.view.dialog;

import com.bustomi.bookstorepos.entity.master.Item;
import com.bustomi.bookstorepos.manager.SpringManager;
import com.bustomi.bookstorepos.service.ItemService;
import com.bustomi.bookstorepos.view.tablemodel.HurufRender;
import com.bustomi.bookstorepos.view.tablemodel.TabelModelBarcode;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import org.apache.bcel.generic.BREAKPOINT;

/**
 *
 * @author PacuL
 */
public class DialogCetakBarcode extends javax.swing.JDialog {

    private TabelModelBarcode modelBarcode;
    // paging utility
    private Integer totalRows = 0;
    private Integer pageNumber = 1;
    private Integer totalPage = 1;
    private Integer rowsPerPage = 15;
    
    public DialogCetakBarcode() {
        setModal(true);
        initComponents();
        modelBarcode=new TabelModelBarcode();
        jTable1.setModel(modelBarcode);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(new HurufRender());
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new HurufRender());
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new HurufRender());
        jTable1.getColumnModel().getColumn(3).setCellRenderer(new HurufRender());  
        jTable1.getColumnModel().getColumn(4).setCellRenderer(new HurufRender()); 
//        jTable1.getColumnModel().getColumn(5).setCellRenderer(new HurufRender()); 
        jTable1.getColumnModel().getColumn(6).setCellRenderer(new HurufRender()); 
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPortX1 = new com.bustomi.bookstorepos.component.ViewPortX();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelXBack1 = new com.bustomi.bookstorepos.component.PanelXBack();
        panelX1 = new com.bustomi.bookstorepos.component.PanelX();
        jLabel1 = new javax.swing.JLabel();
        textFieldXNama = new com.bustomi.bookstorepos.component.TextFieldX();
        buttonMin1 = new com.bustomi.bookstorepos.component.ButtonMin();
        jLabelInfo = new javax.swing.JLabel();
        panelX2 = new com.bustomi.bookstorepos.component.PanelX();
        buttonYellow1 = new com.bustomi.bookstorepos.component.ButtonYellow();
        buttonRed1 = new com.bustomi.bookstorepos.component.ButtonRed();
        jScrollPaneDaftar1 = new javax.swing.JScrollPane();
        panelX3 = new com.bustomi.bookstorepos.component.PanelX();
        jComboBoxPage = new javax.swing.JComboBox();
        btnFirst = new com.bustomi.bookstorepos.component.ButtonMin();
        btnPrevious = new com.bustomi.bookstorepos.component.ButtonMin();
        jLabel5 = new javax.swing.JLabel();
        txtPageNumber = new com.bustomi.bookstorepos.component.TextFieldX();
        lblPageOf = new javax.swing.JLabel();
        btnNext = new com.bustomi.bookstorepos.component.ButtonMin();
        btnLast = new com.bustomi.bookstorepos.component.ButtonMin();
        btnRefresh = new com.bustomi.bookstorepos.component.ButtonMin();
        lblTotalRecord = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setOpaque(false);
        viewPortX1.add(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelX1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        panelX1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Masukan Kode :");

        textFieldXNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldXNamaKeyPressed(evt);
            }
        });

        buttonMin1.setText("Filter");
        buttonMin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMin1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelX1Layout = new javax.swing.GroupLayout(panelX1);
        panelX1.setLayout(panelX1Layout);
        panelX1Layout.setHorizontalGroup(
            panelX1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelX1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldXNama, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonMin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelX1Layout.setVerticalGroup(
            panelX1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelX1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelX1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldXNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buttonMin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jLabelInfo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelInfo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo.setText("Cetak Barcode");
        jLabelInfo.setName(""); // NOI18N

        panelX2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        buttonYellow1.setText("Cetak Terpilih");
        buttonYellow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonYellow1ActionPerformed(evt);
            }
        });
        panelX2.add(buttonYellow1);

        buttonRed1.setText("Cancel");
        buttonRed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRed1ActionPerformed(evt);
            }
        });
        panelX2.add(buttonRed1);

        jScrollPaneDaftar1.setOpaque(false);
        jScrollPaneDaftar1.setViewport(viewPortX1);

        panelX3.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 1, true));

        jComboBoxPage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "15", "20", "25", " " }));
        panelX3.add(jComboBoxPage);

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        panelX3.add(btnFirst);

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        panelX3.add(btnPrevious);

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Page");
        panelX3.add(jLabel5);

        txtPageNumber.setText("0");
        txtPageNumber.setPreferredSize(new java.awt.Dimension(35, 20));
        panelX3.add(txtPageNumber);

        lblPageOf.setForeground(java.awt.Color.white);
        lblPageOf.setText("dari 0.");
        panelX3.add(lblPageOf);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        panelX3.add(btnNext);

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        panelX3.add(btnLast);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        panelX3.add(btnRefresh);

        lblTotalRecord.setForeground(java.awt.Color.white);
        lblTotalRecord.setText("Pages.");
        panelX3.add(lblTotalRecord);

        javax.swing.GroupLayout panelXBack1Layout = new javax.swing.GroupLayout(panelXBack1);
        panelXBack1.setLayout(panelXBack1Layout);
        panelXBack1Layout.setHorizontalGroup(
            panelXBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXBack1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelXBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDaftar1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                    .addGroup(panelXBack1Layout.createSequentialGroup()
                        .addComponent(panelX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelX2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelX3, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelXBack1Layout.setVerticalGroup(
            panelXBack1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXBack1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneDaftar1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(panelX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelXBack1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void buttonMin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMin1ActionPerformed
        cari();
        
    }//GEN-LAST:event_buttonMin1ActionPerformed

    private void buttonYellow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonYellow1ActionPerformed
        
        if (modelBarcode.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Data kosong");   
            return;
        }
        
        List<Item> list=new ArrayList<>();
        
        for (Item item1 : modelBarcode.getList()) {
            if (item1.getPilih() != null) {
                if (item1.getPilih() ) {
                    list.add(item1);                                        
                }                
            }
        }
        
        if(list.isEmpty()){
            JOptionPane.showMessageDialog(this, "Tidak ada data yang dipilih ");  
        }else{  
            
            List<Item> itemSource=new ArrayList<>();
            
            for (Item item : list) {
                if (item.getJmlhCetak() != null){
                    if (item.getJmlhCetak() > 0) {
                        for (int i = 0; i < item.getJmlhCetak(); i++) {
                            itemSource.add(item);
                        }
                    }                    
                }                
            }
            
            if (itemSource.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Jumlah cetak tidak valid");
                return;
            }
            
            try {
                InputStream inputStream=getClass().getResourceAsStream("/com/bustomi/d3ti/uns/report/cetakbarcode.jasper");

                JRDataSource dataSource=new JRBeanCollectionDataSource(itemSource, false);
                Map<String, Object> map=new HashMap<>();
                map.put(JRParameter.REPORT_DATA_SOURCE, dataSource);
                map.put(JRParameter.REPORT_LOCALE, new Locale("in", "ID"));
                map.put("TOKO", "UNSBookstore");

                JasperPrint jasperPrint=JasperFillManager.fillReport(inputStream, map);
                DialogLaporan dialogLaporan=new DialogLaporan(jasperPrint);
                dialogLaporan.setLocationRelativeTo(null);
                dialogLaporan.setVisible(true);
            } catch (JRException ex) {
                Logger.getLogger(DialogCetakBarcode.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
    }//GEN-LAST:event_buttonYellow1ActionPerformed

    private void buttonRed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRed1ActionPerformed
        dispose();
    }//GEN-LAST:event_buttonRed1ActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        pageNumber = 1;
        initDefaultValue();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if (pageNumber > 1) {
            pageNumber -= 1;
            initDefaultValue();
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (pageNumber < totalPage) {
            pageNumber += 1;
            initDefaultValue();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        pageNumber = totalPage;
        initDefaultValue();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        initDefaultValue();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void textFieldXNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldXNamaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cari();
        }
    }//GEN-LAST:event_textFieldXNamaKeyPressed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bustomi.bookstorepos.component.ButtonMin btnFirst;
    private com.bustomi.bookstorepos.component.ButtonMin btnLast;
    private com.bustomi.bookstorepos.component.ButtonMin btnNext;
    private com.bustomi.bookstorepos.component.ButtonMin btnPrevious;
    private com.bustomi.bookstorepos.component.ButtonMin btnRefresh;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.bustomi.bookstorepos.component.ButtonMin buttonMin1;
    private com.bustomi.bookstorepos.component.ButtonRed buttonRed1;
    private com.bustomi.bookstorepos.component.ButtonYellow buttonYellow1;
    private javax.swing.JComboBox jComboBoxPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JScrollPane jScrollPaneDaftar1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPageOf;
    private javax.swing.JLabel lblTotalRecord;
    private com.bustomi.bookstorepos.component.PanelX panelX1;
    private com.bustomi.bookstorepos.component.PanelX panelX2;
    private com.bustomi.bookstorepos.component.PanelX panelX3;
    private com.bustomi.bookstorepos.component.PanelXBack panelXBack1;
    private com.bustomi.bookstorepos.component.TextFieldX textFieldXNama;
    private com.bustomi.bookstorepos.component.TextFieldX txtPageNumber;
    private com.bustomi.bookstorepos.component.ViewPortX viewPortX1;
    // End of variables declaration//GEN-END:variables
    
    private void initDefaultValue() {
        
        ItemService service=SpringManager.getInstance().getBean(ItemService.class);                
        
        rowsPerPage = Integer.valueOf(jComboBoxPage.getSelectedItem().toString());
        totalRows = service.countRows();
        Double dblTotPage = Math.ceil(totalRows.doubleValue()/rowsPerPage.doubleValue());
        totalPage = dblTotPage.intValue();
        if (pageNumber == 1) {
            btnFirst.setEnabled(false);
            btnPrevious.setEnabled(false);
        } else {
            btnFirst.setEnabled(true);
            btnPrevious.setEnabled(true);
        }

        if (pageNumber.equals(totalPage)) {
            btnNext.setEnabled(false);
            btnLast.setEnabled(false);
        } else {
            btnNext.setEnabled(true);
            btnLast.setEnabled(true);
        }

        txtPageNumber.setText(String.valueOf(pageNumber));
        lblPageOf.setText(" of " + totalPage + " ");
        lblTotalRecord.setText("Total Record " + totalRows + " rows.");

        List<Item> list = service.findAll(pageNumber, rowsPerPage);
        modelBarcode.load(list);
    }
    
    private void cari(){
        String nama=textFieldXNama.getText();
        ItemService  service=SpringManager.getInstance().getBean(ItemService.class);
        Item item=service.find(nama);
        if (item == null) {
            JOptionPane.showMessageDialog(this, "Barang dengan kode "+nama+" tidak ditemukan");
        }else{
            modelBarcode.tambahsatu(item);
        }
    }
}
